### ISSUE TITLE
Justificado de párrafos

### ISSUE THREAD

**Issue by ajmatas** [hortfrubiotech/hortfrubiotech.github.io#11]
Para los párrafos, si queremos que estén justificados, se puede usar `<div style="text-align: justify"> your-text-here </div>` en cada uno de ellos o mediante css definiendo el estilo párrafo por defecto.

**Comment by Legodark** [comment]
hago la prueba en mi repositorio y te digo

**Comment by Legodark** [comment]
vale @ajmatas he añadido el codigo a page.html y funciona, se quedaría así 
`<div style="text-align: justify"> 
    {{ content }}
	{% if page.comments %}
  </div>`
El problema es que me mueve el reloj a la derecha. Opinión sobre esto?
