### ISSUE TITLE
Usar una imagen-icono no genérica

### ISSUE THREAD

**Issue by ajmatas** [hortfrubiotech/hortfrubiotech.github.io#5]
Buscar o hacer una nueva imagen o icono y reemplazar la que tenemos ahora para evitar problemas de licencias.

**Comment by Legodark** [comment]
[https://pixabay.com/es/tierra-globo-nacimiento-nuevo-661447/](url)
![earth-661447_1920](https://user-images.githubusercontent.com/29204863/28566708-41195084-7130-11e7-8104-1ec25e11d797.png)
Imagen sin copyrigth.

**Comment by Legodark** [comment]
https://pixabay.com/es/frutas-aceitunas-aceite-olivo-1984336/
![avatar-icon](https://user-images.githubusercontent.com/29204863/28567952-70a38276-7134-11e7-9eda-1385b7332b1a.png)
Imagen sin copyrigth.

**Comment by Legodark** [comment]
![avatar-icon](https://user-images.githubusercontent.com/29204863/30051172-488d91d8-9221-11e7-9604-78d252d718b5.png)
![1](https://user-images.githubusercontent.com/29204863/30051175-4ddab7e2-9221-11e7-9e1b-560220f119aa.jpg)
Imagenes actualizadas, ambas son de libre uso.
