### ISSUE TITLE
Cambiar el título principal de la pagina inicial

### ISSUE THREAD

**Issue by ajmatas** [hortfrubiotech/hortfrubiotech.github.io#6]
El título, ahora AGR226, debería ser el nombre del grupo "Mejora y Biotecnología de Especies Hortofrutícolas"

**Comment by Legodark** [comment]
Me lo asigno para modificarlo

**Comment by ajmatas** [comment]
Gracias @Legodark

**Comment by Legodark** [comment]
Hecho @ajmatas, dejo abierto el issue para que veas como queda antes de cerrarlo

**Comment by ajmatas** [comment]
¿Se puede usar un tamaño de fuente un poco menor para que quede el título en dos líneas? En mi pantalla ocupa cuatro líneas y desplaza todo el contenido muy abajo.

**Comment by Legodark** [comment]
Hago la prueba en mi repositorio y te digo.

**Comment by Legodark** [comment]
ya debe de verse mas pequeño @ajmatas , el problema esta en que solo se puede usar las etiquetas `<h>` ya que hay que modificarlo en el html al que enlaza index.md que es page.html en _layouts

**Comment by Legodark** [comment]
He encontrado otra forma de cambiar el mamaño y la fuente añadiendo esto al codigo`<font size=6 face="cursive">`

**Comment by Legodark** [comment]
@ajmatas mira a ver que te parece la fuente que le he puesto, al final lo he modificado por css, que se puede jugar mas con el tamaño y con un monton mas de fuentes.

He añadido lo siguiente para que funcione:
`<div id="mih1">{{ page.title }}</div>` en page.html
`#mih1{
  font-family: 'Lobster', cursive;
  font-size: 60px;
}` en main.css
`<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">` en head.html

**Comment by ajmatas** [comment]
Está bien poder controlarla desde css, pero yo mantendría limitado el número de fuentes diferentes en la web. Un par como mucho: una tipo Sans para los títulos y la serif que hay para los párrafos.

**Comment by Legodark** [comment]
vale, entonces dejo la fuente actual en el titulo o la cambio?, a mi me gusta como queda :).

**Comment by Legodark** [comment]
cambiada fuente de letra del menu, de los titulos de las paginas y añadida foto de fondo
